services:
  - type: web
    name: fake-news-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: API_KEY
        sync: false
    healthCheckPath: /health